table DadosFinanceiros
	lineageTag: 3882ba05-6524-4728-9eae-c3d25338518c

	measure _mValorTotal = SUM(DadosFinanceiros[Valor])
		lineageTag: a1e7db6b-41a5-4c89-9d63-7e725fe1e906

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure _mValorTotalReceita = CALCULATE(SUM(DadosFinanceiros[Valor]),DadosFinanceiros[Tipo] = "Receitas")
		lineageTag: a93c80c2-1919-4c14-aaee-1c2903d4ebb1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure _mValorTotalDespesas = CALCULATE(SUM(DadosFinanceiros[Valor]),DadosFinanceiros[Tipo] = "Despesas")
		lineageTag: de6dbbd4-13c8-4f1e-bcb6-62ba47c9c1da

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure _mMargemDeLucro = DIVIDE([_mLucro],[_mValorTotalReceita],0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: fed96ed2-d8ee-4761-85ea-71b06f479226

	measure _mMediaDespesas = CALCULATE(AVERAGE(DadosFinanceiros[Valor]),DadosFinanceiros[Tipo] = "Despesas")
		lineageTag: 1bd0726a-9e99-4396-9543-6ff67b07bdc7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure _mLucro = [_mValorTotalReceita] - [_mValorTotalDespesas]
		lineageTag: 67887072-5197-4b60-92e1-717b3c412cf4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Tipo
		dataType: string
		lineageTag: 7161771e-11cd-44d4-8570-b3f8a9b405fb
		summarizeBy: none
		sourceColumn: Tipo

		annotation SummarizationSetBy = Automatic

	column Componente
		dataType: string
		lineageTag: 1f92156b-daba-436d-b502-1c8abe7c9248
		summarizeBy: none
		sourceColumn: Componente

		annotation SummarizationSetBy = Automatic

	column DATA
		dataType: dateTime
		formatString: Short Date
		lineageTag: a9386020-9d5c-45c9-8375-dc65468bf5f7
		summarizeBy: none
		sourceColumn: DATA

		variation Variation
			isDefault
			relationship: 1253a9d7-67ce-4961-ab4c-db0d732d7639
			defaultHierarchy: LocalDateTable_72b59eca-959c-49d6-aa76-197294629dc6.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Valor
		dataType: double
		lineageTag: 7df3e870-a52b-4cce-a3f7-4994b42f1dce
		summarizeBy: sum
		sourceColumn: Valor

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition DadosFinanceiros = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\diego\Downloads\DadosFinanceiros\DadosFinanceiros.xlsx"), null, true),
				    DadosFinanceiros_Sheet = Fonte{[Item="DadosFinanceiros",Kind="Sheet"]}[Data],
				    #"Tipo Alterado" = Table.TransformColumnTypes(DadosFinanceiros_Sheet,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}, {"Column7", type text}, {"Column8", type text}, {"Column9", type text}, {"Column10", type text}, {"Column11", type text}, {"Column12", type text}, {"Column13", type text}, {"Column14", type text}, {"Column15", type text}, {"Column16", type text}, {"Column17", type text}, {"Column18", type text}, {"Column19", type text}, {"Column20", type text}, {"Column21", type text}, {"Column22", type text}, {"Column23", type text}, {"Column24", type text}, {"Column25", type text}, {"Column26", type text}, {"Column27", type text}, {"Column28", type text}, {"Column29", type text}, {"Column30", type text}, {"Column31", type text}, {"Column32", type text}, {"Column33", type text}, {"Column34", type text}, {"Column35", type text}, {"Column36", type text}, {"Column37", type text}, {"Column38", type text}}),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"Tipo Alterado", [PromoteAllScalars=true]),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Tipo", type text}, {"Componente", type text}, {"01/01/2019", Int64.Type}, {"01/02/2019", type number}, {"01/03/2019", type number}, {"01/04/2019", Int64.Type}, {"01/05/2019", type number}, {"01/06/2019", Int64.Type}, {"01/07/2019", Int64.Type}, {"01/08/2019", Int64.Type}, {"01/09/2019", Int64.Type}, {"01/10/2019", Int64.Type}, {"01/11/2019", Int64.Type}, {"01/12/2019", Int64.Type}, {"01/01/2020", Int64.Type}, {"01/02/2020", Int64.Type}, {"01/03/2020", Int64.Type}, {"01/04/2020", Int64.Type}, {"01/05/2020", Int64.Type}, {"01/06/2020", Int64.Type}, {"01/07/2020", Int64.Type}, {"01/08/2020", Int64.Type}, {"01/09/2020", Int64.Type}, {"01/10/2020", Int64.Type}, {"01/11/2020", Int64.Type}, {"01/12/2020", Int64.Type}, {"01/01/2022", Int64.Type}, {"01/02/2022", Int64.Type}, {"01/03/2022", Int64.Type}, {"01/04/2022", Int64.Type}, {"01/05/2022", Int64.Type}, {"01/06/2022", Int64.Type}, {"01/07/2022", Int64.Type}, {"01/08/2022", Int64.Type}, {"01/09/2022", Int64.Type}, {"01/10/2022", Int64.Type}, {"01/11/2022", Int64.Type}, {"01/12/2022", Int64.Type}}),
				    #"Colunas Não Dinâmicas" = Table.UnpivotOtherColumns(#"Tipo Alterado1", {"Tipo", "Componente"}, "Atributo", "Valor"),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Colunas Não Dinâmicas",{{"Atributo", "DATA"}}),
				    #"Linhas Classificadas" = Table.Sort(#"Colunas Renomeadas",{{"DATA", Order.Descending}}),
				    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Linhas Classificadas",{{"DATA", type date}})
				in
				    #"Tipo Alterado2"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

